#!/usr/bin/env bash
# Installing nginx
# then quering it with curl at its root to return the string "Hello World!"

sudo apt-get -y update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
