#!/usr/bin/env bash
# Configuring your Nginx server so that /redirect_me is redirecting to another page

sudo sed -i '/server_name _;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
