#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header on web-01 and web-02

apt-get -y update
apt-get -y install nginx
sudo sed -i '/listen 80 default_server/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
echo "Hello World" | sudo tee file /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee file /var/www/html/404.html
sudo service nginx restart
