#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

h=0
while (( h < 13 ))
do
	m=1
	echo "Hour: $h"
		while (( m < 61 ))
		do
			echo "$m"
			((m++))
		done
	((h++))
done
